#! /bin/bash

set -xe


#	remove stupid things from Plasma, generic KDE launchers, breeze cursors, etc.

rm -rf \
	/usr/share/applications/htop.desktop \
	/usr/share/applications/links2.desktop \
	/usr/share/applications/mc.desktop \
	/usr/share/applications/mcedit.desktop \
	/usr/share/applications/nsnake.desktop


#	let nsnake be reachable through $PATH.

ln -svf /usr/games/nsnake /usr/bin/nsnake


#	add oh-my-zsh.

git clone https://github.com/robbyrussell/oh-my-zsh.git /etc/skel/.oh-my-zsh


#	add support for AppImages,

echo -e "PATH=$PATH:/Applications\n" >> /etc/environment
sed -i "s|secure_path\=.*$|secure_path=\"$PATH:/Applications\"|g" /etc/sudoers
sed -i "/env_reset/d" /etc/sudoers


#	use mksh and zsh in userland.

ln -svf /bin/mksh /bin/sh

sed -i 's+SHELL=/bin/sh+SHELL=/bin/zsh+g' /etc/default/useradd
sed -i 's+DSHELL=/bin/bash+DSHELL=/bin/zsh+g' /etc/adduser.conf


#	workaround for vmetal

ln -sv /usr/lib/x86_64-linux-gnu/libffi.so.7.1.0 /usr/lib/x86_64-linux-gnu/libffi.so.6


#	add xdg_dir environment variables

echo -e "XDG_CONFIG_DIRS=/etc/xdg" >> /etc/environment
echo -e "XDG_DATA_DIRS=/usr/local/share:/usr/share" >> /etc/environment


# #	add documentation
# #FIXME Change documentation.

# {
# 	printf "%s %s\n" \
# 		Compendium.pdf		"https://github.com/Nitrux/iso-tool/raw/master/configs/other/compendium_offline.pdf" \
# 		FAQ.pdf				"https://github.com/Nitrux/iso-tool/raw/master/configs/other/faq_offline.pdf"
# } | {
# 	while read name url; do
# 		axel -a -q -o /etc/skel/Desktop/$name "$url"
# 	done
# }

# mv /etc/skel/Desktop/Compendium.pdf	/etc/skel/Desktop/Nitrux\ —\ Compendium.pdf
# mv /etc/skel/Desktop/FAQ.pdf /etc/skel/Desktop/Nitrux\ —\ FAQ.pdf

